name    'natewalck-munki_appliance'
version '0.1.0'
license 'Apache License, Version 2.0'
summary 'Munki Appliance Module'
description 'Puppet Module for configuring the munki appliance'
dependency 'puppetlabs/apache', '0.x'
dependency 'puppetlabs/vcsrepo', '0.x'
dependency 'stahnma/epel', '0.x'
dependency 'thias/samba', '0.x'
